
[[redirects]]
  from = "/"
  to = "/previews.json"
  status = 200

[[redirects]]
  from = "/shows"
  to = "/previews.json"
  status = 200

[[redirects]]
  from = "/show/:splat/*"
  to = "/shows/:splat.json"
  status = 200

[[redirects]]
  from = "/id/:splat/*"
  to = "/show/:splat.json"
  status = 200
  
[[redirects]]
  from = "/genre/:splat/*"
  to = "/genre/:splat.json"
  status = 200

[[redirects]]
  from = "/*"
  to = "/invalid.json"
  status = 500

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
